### ISSUE TITLE
attr_accessor :bearer_token has to be changed due to PR #9 change

### ISSUE THREAD

**Issue by rubytester** [chef-partners/vmware-vra-gem#12]
As a result of PR #9 there is a buggy side-effect because of `attr_accessor: bearer_token`.

User is allowed to set `client.bearer_token="xyz"` and the value of `@bearer_token` is a 'String' (and should be a `PasswordMasker`. )

2 ways to fix this bug:

1. [Get rid of ability to read or write `:bearer_token`](https://github.com/chef-partners/vmware-vra-gem/blob/master/lib/vra/client.rb#L26). Do you need people to set that token from outside? Is there a condition where you can initialize the client without user/password and instead just provide a known token?

2. if you want to read and write `bearer_token` then provide PasswordMasker wrapper methods:

```ruby
def bearer_token=foo
  @bearer_token = PasswordMasker.new foo
end

def bearer_token
   @bearer_token.value if @bearer_token
end
```

I would vote for number 1. Since you must have a username and password setting bearer_token is not needed unless there is a compelling user need for this. 

Thoughts?

**Comment by adamleff** [comment]
Fixing in #14 - closing issue.
