### ISSUE TITLE
Machine status is MachineActivated causing errors (VRA7)

### ISSUE THREAD

**Issue by stevehedrick** [chef-partners/vmware-vra-gem#18]
Doing some work with chef provisioning and a new test VRA7 environment, I'm running into the following error:

```
    - Powering on windows_test1 if needed
    - Machine status is MachineActivated. Submitting power-on request for resource 6947e880-7ff0-4609-971b-c7f11821cae2
    ================================================================================
    Error executing action `converge` on resource 'machine[windows_test1]'
    ================================================================================

    Vra::Exception::NotFound
    ------------------------
    No power-on action found for resource 6947e880-7ff0-4609-971b-c7f11821cae2

```

This error isn't coming up every time, it's intermittent.  I think that the issue might be the machine status returning `MachineActivated`.  It's starting the machine already, and not making a start action available.  I'm going to guess the issue is being primarily caused by slowness in this test-environment.  Where it doesn't error out my suspicion is that it's moving along quickly enough that time to get to a `TurningOn` state by the time it's checked, preventing the error from showing up.

I've tried with making a change to the resource.machine_turning_on? method to allow `MachineActivated` as well as `TurningOn` and it looks to do the trick.  The other method I could think of was to insert a wait for the state to change from `MachineActivated` to something else, then recheck, but that seemed heavier.  The heavier wait method might be better if it's actually possible to go from `MachineActivated` to other states than turning on, but from what I can tell, `TurningOn` and `On` are both children of the `MachineActivated` state.  The VPMS master workflow shows tranisitoning directly from `MachineActivated` to the Deactivate/Unprovision/Disposal states.

**Comment by adamleff** [comment]
@stevehedrick thanks for your issue. To be honest, this gem nor the vRA-related Chef plugins have been tested against vRA 7, so perhaps this is a new state?

I think it's a reasonable change to treat `MachineActivated` as a valid turning-on state, and if we find that it introduces some weirdness, we can revisit. Would you be willing to submit a PR for that?

**Comment by stevehedrick** [comment]
I'll get one ready for you, thanks!  BTW other than this one issue, so far it's working perfectly fine on vRA 7.

**Comment by adamleff** [comment]
That is super-awesome news!
