### ISSUE TITLE
`Vra::Exception::HTTPError` initialized incorrectly

### ISSUE THREAD

**Issue by regularfry** [chef-partners/vmware-vra-gem#23]
https://github.com/chef-partners/vmware-vra-gem/blob/master/lib/vra/client.rb#L127 is the offending line.  `HTTPError` wants to be passed an `opts` hash, but `client.rb` attempts to initialise it with a `String`.  This causes:

````
TypeError: no implicit conversion of Symbol into Integer
from /Users/ayo07/scratch/vrealize/vagrant-vrealize/.rv/2.2.3/gem_home/gems/vmware-vra-1.5.1/lib/vra/exceptions.rb:31:in `[]'
````

**Comment by regularfry** [comment]
I suspect this actually wants to be creating a `RequestError`.

**Comment by adamleff** [comment]
@regularfry: thanks for opening this issue. I actually think the correct approach is to use `#raise_http_exception` like we do in `#http_get` and `#http_post` - I think I just missed updating `#http_head` when I created that helper method. Let me look through the code to ensure I'm not missing something and then I'll adjust it accordingly.

**Comment by adamleff** [comment]
@regularfry v1.5.3 has been pushed to Rubygems with this fix. Thanks again for raising the issue.
