### ISSUE TITLE
fork of this gem

### ISSUE THREAD

**Issue by logicminds** [chef-partners/vmware-vra-gem#24]
Hey,  I ended up forking this gem and re-releasing as a new gem.  Since this gem seems to be tied to chef and knife I wanted to make something more independent.   I also removed the yajl library so the gem would be more portable in cases where this is run on a windows platform. 

Not sure if you want to mention this in your readme.md file but If people are not using chef they now have an alternative.   I'll also be adding a few features as well that didn't seem like a good fit for the original gem.

https://github.com/nwops/vra-restapi

**Comment by adamleff** [comment]
@logicminds you are totally within your right to fork this gem if you feel it doesn't suit your needs. It was deliberately designed to NOT be Chef specific. Some of the gems in use happen to be used by Chef, but that was for ease-of-use and consistency, not a statement of being tied to Chef.

Thanks for letting us know, and happy coding. :)
