### ISSUE TITLE
Incompatible with vagrant 1.8+ (at least)

### ISSUE THREAD

**Issue by regularfry** [chef-partners/vmware-vra-gem#26]
I've been working on a vagrant plugin to make a VRealize provisioner.  I've run into a small problem: the version specifications of the `rest-client` gem required by `vmware-vra` and `vagrant-share`, a closed-source vagrant component, are incompatible.  `vmware-vra` specifies `~> 1.8`, while `vagrant-share` specifies `~> 1.6.0`.

Would a PR to remove the `rest-client` dependency from `vmware-vra` and replace it with plain Net::HTTP be a suitable fix?  It doesn't look like `RestClient` is being used too heavily.  Alternatively, could the `rest-client` version specifier be relaxed?

**Comment by adamleff** [comment]
As long as the PR maintains parity with the existing gem and there is appropriate test coverage, this would be a fine change. :)

**Comment by adamleff** [comment]
Relaxing the rest-client version specifier is an option to. Feel free to submit a PR for that after verifying it solves your issue!

**Comment by regularfry** [comment]
https://github.com/chef-partners/vmware-vra-gem/pull/28 is a PR for removing rest-client.  It's slightly more intrusive than I thought it was going to be, but it Works For Me(tm).  Happy to make style changes if required.

**Comment by logicminds** [comment]
Is this still an issue?  Looking to make a vagrant plugin too.  Also found: https://github.com/nhudacin/vagrant-vrealize

**Comment by jjasghar** [comment]
I think this isn't relevant anymore. If it is please reopen it with the error you're seeing and we can debug from there.
