### ISSUE TITLE
catalog_request SSLError

### ISSUE THREAD

**Issue by wareagl** [chef-partners/vmware-vra-gem#30]
catalog.request does not seem to inherit verify_ssl settings in Client.new.  There also doesn't seem to be a way to pass verify_ssl setting in catalog.request.  Is this something that can be changed?

**Comment by cbalducci** [comment]
it's been fixed in this fork

https://github.com/nwops/vra-restapi

don't know why hasn't be merged tho

**Comment by bvandgrift** [comment]
@cbalducci , @wareagl - since that fork was last committed to, `rest-client` was removed for HTTP communication in favor of a custom solution. merging vra-restapi at this point looks problematic.

**Comment by cbalducci** [comment]
@bvandgrift i see you've already submitted a PR which fixes this issue. Let's hope it gets merged soon

**Comment by logicminds** [comment]
This is now fixed.  You can ignore certificate verification via the following.

```ruby
Vra::Client.new(
  username: username,
  password: password,
  tenant: 'vsphere.local',
  base_url: server
  verify_ssl: false   
)
```

**Comment by logicminds** [comment]
@jjasghar please close this since it is resolved.
