### ISSUE TITLE
why is chefstyle a runtime dependency?

### ISSUE THREAD

**Issue by logicminds** [chef-partners/vmware-vra-gem#44]
The chefstyle dependency is causing dependencies on ruby versions 2.2 or newer.  Chefstyle seems more like a development dependency rather than a runtime dependency.  Can we change this?

**Comment by logicminds** [comment]
@jjasghar can you answer this.  I ended up just force installing this gem since I run ruby 2.1.9.  

Chefstyle is cramping my style!

**Comment by jjasghar** [comment]
Ah yeah this seems reasonable. What version of the Chefdk (assuming you do) are you running?

**Comment by logicminds** [comment]
I am using this gem directly so I don't know what chefdk even is.  Also using in conjunction with kitchen-vra gem too.

**Comment by jjasghar** [comment]
Ah ok. So I'm back from ChefConf now, and I'm going to be working on releasing these changes ASAP. Thanks for your patience. (And reaching out on Slack)
