### ISSUE TITLE
usage of openssl raises error

### ISSUE THREAD

**Issue by logicminds** [chef-partners/vmware-vra-gem#45]
The call here tries to use openssl but the openssl library is not loaded.  This is caused when using this gem directly without other chef tools that would have loaded the library already.

The fix is to just `require 'openssl'` in the http.rb file.

https://github.com/chef-partners/vmware-vra-gem/blob/master/lib/vra/http.rb#L41

**Comment by jjasghar** [comment]
Oh interesting. that's for that. Can you put in a PR for this? I can release a bug fix gem asap.
