### ISSUE TITLE
undefined method `[]' for nil:NilClass if data for json content is of single entity

### ISSUE THREAD

**Issue by rameshkumar20** [chef-partners/vmware-vra-gem#55]
### Versions:

* Version of vmware-vra-gem:2.3.0
* Version of chef:12.21.4
* Version of ruby: 2.3.1p112 (2016-04-26 revision 54768)

### Platform Details

* Version of vRA: 7.3.0
* Version of ESXi: NA

### Scenario:

After upgrade from vRA6 to vRA7, trying to provision using chef provisioning by pointing to latest vmware-vra gem.
And for already provisioned VMs, it keep failing with below error:
`[2017-08-28T22:38:38+05:30] DEBUG: Re-raising exception: NoMethodError - machine[APP101] (provision::single_box line 22) had an error
: NoMethodError: undefined method `[]' for nil:NilClass
C:/Users/username/AppData/Local/chefdk/gem/ruby/2.3.0/gems/vmware-vra-2.3.0/lib/vra/resource.rb:169:in `ip_addresses'
`
### Fix Applied:
Changed resource.rb line#169 to
`      data_zero = JSON.parse(resource_views.body)["content"][0]["data"]["ip_address"]
      if JSON.parse(resource_views.body)["content"][1].nil?
        data_one = ""
      else
        data_one = JSON.parse(resource_views.body)["content"][1]["data"]["ip_address"]    
      end
`

### Steps to Reproduce:

1. Do a provisioning on vRA6.
2. Upgrade vRA to 7
3. Load vRA 7 supported gems interms of chef-provisioning-vra and vmware-vra 
4. Trigger the chef provisioning on the previously provisioned VM.

### Expected Result:
Expected to provision the VMs and execute the provided run list.

### Actual Result:
Failed with error:
`[2017-08-28T22:38:38+05:30] DEBUG: Re-raising exception: NoMethodError - machine[APP101] (provision::single_box line 22) had an error
: NoMethodError: undefined method `[]' for nil:NilClass
C:/Users/username/AppData/Local/chefdk/gem/ruby/2.3.0/gems/vmware-vra-2.3.0/lib/vra/resource.rb:169:in `ip_addresses'`

**Comment by lgustafson** [comment]
This looks like a different scenario but the same underlying issue as #65
