### ISSUE TITLE
Extra Parameters Not Being Sent to vRA

### ISSUE THREAD

**Issue by rkoteck** [chef-partners/vmware-vra-gem#73]
### Versions:
* Version of vmware-vra-gem: 2.6.1
* Version of kitchen-vra gem: 2.6.0
* Version of test-kitchen gem: 1.24.0
* Version of ChefDK: 3.8.14
* Version of Chef Client: 14.10.9
* Version of ruby: 2.5.3p105

### Platform Details

* Version of vRA: 7.5

### Scenario:
I'm trying to pass some extra_parameters to vRA to provision a virtual machine with test kitchen.  We are passing a public key to the virtual machine so the user can ssh to the machine.  The authentication to vRA succeeds and starts to build the machine.  The machine builds successfully but cannot ssh to the box.  From what I see on the vRA/vRO side, the parameters are not getting passed.

### Steps to Reproduce:
Here is a sample of what my kitchen.yml looks like:

driver:
  name: vra
  username: <%= ENV['USERNAME'] %>@domain.com
  password: <%= ENV['MYPASS'] %>
  tenant: dfs
  base_url: https://vra-prod.na.domain.com
  verify_ssl: false
  request_timeout: 1200
  private_key_path: C:\Users\<%= ENV['USERNAME'] %>\.ssh\id_rsa

platforms:
  - name: ChefDK
    driver:
      catalog_id: abcd1234-ab12-ab12-ab12-abcdef123456
      subtenant_id: abcd1234-ab12-ab12-ab12-abcdef123456
      extra_parameters:
        chefdk.ssh_pub_key:
          type: string
          value: 'ssh-rsa abcd1234.......... user@domain'
        rhelVersion:
          type: string
          value: RHEL7

### Expected Result:
```
$ kitchen create
-----> Starting Kitchen (v1.24.0)
Please report a bug if this causes problems.
-----> Creating <default-ChefDK>...
       Building vRA catalog request...
       Catalog request abcd1234-ab12-ab12-ab12-abcdef123456 submitted.
       Current request status: IN_PROGRESS
Waiting For vRA to collect the IP       Server abcd1234-ab12-ab12-ab12-abcdef123456 (hostname) created. Waiting until ready...
       [SSH] Established
       Server abcd1234-ab12-ab12-ab12-abcdef123456 (hostname) ready.
       Finished creating <default-ChefDK> (13m1.60s).
-----> Kitchen is finished. (13m49.70s)
```

### Actual Result:
```
$ kitchen create
-----> Starting Kitchen (v1.24.0)
Please report a bug if this causes problems.
-----> Creating <default-ChefDK>...
       Building vRA catalog request...
       Catalog request abcd1234-ab12-ab12-ab12-abcdef123456 submitted.
       Current request status: IN_PROGRESS
Waiting For vRA to collect the IP       Server abcd1234-ab12-ab12-ab12-abcdef123456 (hostname) created. Waiting until ready...
       Waiting for SSH service on 10.10.10.10:22, retrying in 3 seconds
       Waiting for SSH service on 10.10.10.10:22, retrying in 3 seconds
       Waiting for SSH service on 10.10.10.10:22, retrying in 3 seconds
       Waiting for SSH service on 10.10.10.10:22, retrying in 3 seconds
       Waiting for SSH service on 10.10.10.10:22, retrying in 3 seconds
       Waiting for SSH service on 10.10.10.10:22, retrying in 3 seconds
       Waiting for SSH service on 10.10.10.10:22, retrying in 3 seconds
       Waiting for SSH service on 10.10.10.10:22, retrying in 3 seconds
       Waiting for SSH service on 10.10.10.10:22, retrying in 3 seconds
       Waiting for SSH service on 10.10.10.10:22, retrying in 3 seconds
```

**Comment by PopPopDevOps** [comment]
Having the same issue with the extra_parameters not passing

**Comment by PopPopDevOps** [comment]
I see this as related...
https://github.com/chef-partners/kitchen-vra/issues/30
